---
title: "The indirect effects of nuclear power plant accidents on population dynamics"
author: 
  - name: Naruki Notsu
    url: https://narukinotsu.github.io/
    affiliation: Osaka School of International Public Policy
  - name: Yosuke Abe
    url: /index.qmd
    affiliation: Mitsubishi UFJ Research and Consulting Co., Ltd.
  - name: Shuko Harada
    affiliation: Osaka School of International Public Policy
date: 2025-04-17
toc: false
---

## Abstract

Most studies have focused on the economic consequences of disaster shocks, but the broader impact on areas outside the disaster remains unclear. Using the shock of the Great East Japan Earthquake and cross-municipality variation in the locations of nuclear power plants unrelated to the earthquake, this paper shows the indirect impact of disasters on population dynamics. The earthquake triggered nuclear power plant accidents, which heightened residents’ risk perceptions of the plants. We find that population inflows to and outflows from municipalities with nuclear power plants decreased after the earthquake. The effects could also be driven by the residents’ risk perceptions and falling land prices. Our findings suggest that policymakers and researchers need to consider the broader extent of disaster effects more carefully.

URL: <https://www.tandfonline.com/doi/full/10.1080/13504851.2025.2493771>

## BibTeX

``` bibtex
@article{notsu_indirect_2025,
    author = {Notsu, Naruki and Abe, Yosuke and Harada, Shuko},
    title = {The indirect effects of nuclear power plant accidents on population dynamics},
    journal = {Applied Economics Letters},
    volume = {0},
    number = {0},
    pages = {1--6},
    year = {2025},
    publisher = {Routledge},
    doi = {10.1080/13504851.2025.2493771},

    URL = {https://doi.org/10.1080/13504851.2025.2493771},
    eprint = {https://doi.org/10.1080/13504851.2025.2493771}
}
```