
- category: Shiny
  description: |
    白地図Japanの全国版を追加し、いずれのアプリケーションも軽量化しました！
  tiles:
    - title: 白地図 Japan
      subtitle: |
        全国版
      href: https://yo5uke.shinyapps.io/hakuchizu_japan/
      code: https://github.com/yo5uke/hakuchizu_japan
      thumbnail: hakuchizu_japan/thumbnail.png
    - title: 白地図 Japan
      subtitle: |
        東日本
      href: https://yo5uke.shinyapps.io/map_east_japan/
      thumbnail: map_east_japan/thumbnail.png
    - title: 白地図 Japan
      subtitle: |
        西日本
      href: https://yo5uke.shinyapps.io/map_west_japan/
      thumbnail: map_west_japan/thumbnail.png