
- category: Shiny
  description: |
    Shinyアプリケーションの一覧です。人口ヒートマップを追加しました（2025/3/22）。
  tiles:
    - title: 課税状況ヒートマップ
      href: https://yo5uke.shinyapps.io/tax_revenue_heatmap/
      code: https://github.com/yo5uke/tax_revenue_heatmap
      thumbnail: tax_revenue_heatmap/thumbnail.png
    - title: 人口ヒートマップ
      subtitle: |
        1980～2020
      href: https://yo5uke.shinyapps.io/japan_population_heatmap/
      code: https://github.com/yo5uke/population_heatmap
      thumbnail: population_heatmap/thumbnail.png
    - title: 白地図 Japan
      subtitle: |
        全国版
      href: https://yo5uke.shinyapps.io/hakuchizu_japan/
      code: https://github.com/yo5uke/hakuchizu_japan
      thumbnail: hakuchizu_japan/thumbnail.png
    - title: 白地図 Japan
      subtitle: |
        東日本
      href: https://yo5uke.shinyapps.io/map_east_japan/
      thumbnail: map_east_japan/thumbnail.png
    - title: 白地図 Japan
      subtitle: |
        西日本
      href: https://yo5uke.shinyapps.io/map_west_japan/
      thumbnail: map_west_japan/thumbnail.png