
- category: Shiny
  description: |
    Shinyアプリケーションの一覧です。人口ヒートマップをアップデートしました（2025/7/21）。
  tiles:
    - title: 地方財政状況マップ
      subtitle: |
        2014 ~ 2023
      href: https://yo5uke.shinyapps.io/tax_revenue_heatmap/
      code: https://github.com/yo5uke/tax_revenue_heatmap
      thumbnail: tax_revenue_heatmap/thumbnail.png
    - title: 課税状況ヒートマップ
      href: https://yo5uke.shinyapps.io/tax_status_heatmap/
      code: https://github.com/yo5uke/tax_status_heatmap
      thumbnail: tax_status_heatmap/thumbnail.png
    - title: 人口ヒートマップ
      subtitle: |
        1980～2020
      href: https://yo5uke-population-heatmap.share.connect.posit.cloud/
      code: https://github.com/yo5uke/population_heatmap
      thumbnail: population_heatmap/thumbnail.png
    - title: 白地図 Japan
      subtitle: |
        全国版
      href: https://yo5uke.shinyapps.io/hakuchizu_japan/
      code: https://github.com/yo5uke/hakuchizu_japan
      thumbnail: hakuchizu_japan/thumbnail.png