
- tiles:
    - title: 白地図 Japan
      subtitle: |
        東日本
      href: https://yo5uke.shinyapps.io/map_east_japan/
      thumbnail: map_east_japan/thumbnail.png
    - title: 白地図 Japan
      subtitle: |
        西日本
      href: https://yo5uke.shinyapps.io/map_west_japan/
      thumbnail: map_west_japan/thumbnail.png