---
title: "Writing Papers with Quarto and Typst"
author: 
  - name: Your Name
    affiliation: Your Affiliation
    email: your-address@example.com
date: 2025-10-21
date-format: long
abstract: |
  {{< lipsum 1 >}}
keywords: [Quarto, Typst, Academic Writing, PDF Generation]
format:
  econ-a4-typst:
    toc: true
    number-sections: true
lang: en
brand: false
bibliography: []
---

## Introduction

@notsu_indirect_2025

{{< lipsum 2 >}}

## Insert Figures

```{r}
#| echo: false

library(ggplot2)

# Create a simple plot
ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point() +
  labs(
    title = "Scatter plot of MPG vs Weight",
    x = "Weight (1000 lbs)",
    y = "Miles per Gallon"
  )
```

## Insert Tables

```{r}
#| echo: false
#| fig-cap: "A simple table showing the first few rows of the mtcars dataset."

library(tinytable)

# Create a simple table
tt(
  head(mtcars),
  notes = "Note: This table shows the first few rows of the mtcars dataset."
)
```

## Mathematical Expressions

$$
E=mc^2
$$

```{=typst}
#bibliography("/references.bib")
```

## Appendix {.unnumbered}

{{< lipsum 3 >}}