---
title: 【WSL】割り当てるメモリを増やす方法
description: |
  WSL はデフォルトでPCの半分のメモリが割り当てられています。
date: 2024-05-31
date-modified: 2026-01-09
categories:
- WSL
- Windows
- 備忘録
aliases:
- /pages/tips/240531_wsl_memory/index.html
---

## はじめに

WSLを使用していて、使えるメモリを増やしたい、そんな時にどうすればよいのか解説します。

デフォルトではPCの半分のメモリがWSLには割り当てられています。

すなわちメモリが8GBのPCであれば4GBが、16GBのPCであれば8GBが割り当てられています。

プロジェクトによってはより多くのメモリを使いたいこともあると思うので、以下の方法を実行してみて下さい。

ちなみにMacではDocker Desktopの設定からResourcesで変更できます。

## 手順

1. エクスプローラーを開く
2. `C:\Users\your-username` と進む
    - 自分の場合だったら `C:\Users\yo5uk`
3. 左上の「新規作成」から「テキストドキュメント」を選び、ファイル名を `.wslconfig` とする
    - 拡張子も全て消して名前を付けてください。`.wslconfig.txt`ではだめです。
    - もし拡張子がデフォルトで表示されない設定の場合は、表示されるよう設定を変更してから行って下さい。
    - エクスプローラー右上の「表示」→「表示」→「ファイル名拡張子」をオンにします。
4. メモ帳など任意のテキストエディタで開く
5. 中身を以下のように記述
    - メモリの部分は好きに置き換えてください。
    - 8GBのPCを使っている場合には、もちろん12GBは割り当てられません。

```{.txt}
[wsl2]
memory=12GB
swap=8GB
processors=4
```

6. 保存して閉じる

以上です。これでWSLに割り当てられるメモリが増えました。

ちなみに`memory`は読んで字のごとくメモリを表しますが、ここでの`swap`は、WSL2が使用するスワップファイルのサイズを設定することを意味します。スワップファイルを適切に設定することで、物理メモリが不足した場合でもシステムの安定性を維持することができます。

また、`processors`はWSL2が使用できる論理プロセッサ(CPUコア)の数を指定します。例えば上記のように`processors=4`と設定すると、WSLは最大4つの論理プロセッサまで使用します。これにより、Windows側のパフォーマンスを確保しつつ、WSLでの作業も快適に行えるバランスの取れた環境を構築できます。

## おわりに

WSLに割り当てるメモリを増やす方法をご紹介しました。

プロジェクトによっては必要になることもあると思うので、ご参考まで。
